-- Database: postgres
--DROP DATABASE if exists "postgres";
/*CREATE DATABASE "postgres"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Ecuador.1252'
    LC_CTYPE = 'Spanish_Ecuador.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
*/	
	
drop table if exists  T_EMPLEADOS cascade;
drop table if exists  T_USUARIOS cascade

CREATE TABLE IF NOT EXISTS  t_empleados
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identificacion character varying(10)  NOT NULL,
	direccion_domicilio character varying(250) ,
    apellidos character varying(100)  NOT NULL,
    correo_electronico character varying(100)  NOT NULL,
    fecha_nacimiento date,
    fecha_vacunacion date,
    nombres character varying(100)  NOT NULL,
    dosis integer,
    telefono character varying(25) ,
    tipo_vacuna character varying(50) ,
    estado_vacunacion boolean,
	
    CONSTRAINT t_empleados_pkey PRIMARY KEY (id),
    CONSTRAINT uk_identificacion_E UNIQUE (identificacion)
);
 
CREATE TABLE IF NOT EXISTS  T_USUARIOS
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    contrasena character varying(100)   NOT NULL,
    identificacion character varying(10)   NOT NULL,
    nombres character varying(100)   NOT NULL,
    rol character varying(50)   NOT NULL,
    CONSTRAINT t_usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT uk_identificacion_U UNIQUE (identificacion)
);

INSERT INTO  t_usuarios(
	 contrasena, identificacion, nombres, rol)
	VALUES ('ADMIN', 'ADMIN', 'ADMINISTRADOR', 'ADMINISTRADOR');